# Generated by Django 4.2 on 2023-10-27 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("balance", "0004_alter_transaction_due_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="transaction",
            name="due_date",
            field=models.DateField(default=datetime.date(2023, 10, 27)),
        ),
    ]
